# Generated by Django 4.1.5 on 2023-02-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_time_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(default=2550754391, max_length=50, verbose_name='qq'),
            preserve_default=False,
        ),
    ]
