# Generated by Django 4.1.5 on 2023-03-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinfo_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_id',
            field=models.IntegerField(choices=[(1, '8:50-9:35'), (2, '9:45-10:30'), (3, '10:45-11:30'), (4, '11:40-12:25'), (5, '13:50-14:35'), (6, '14:45-15:30'), (7, '15:45-16:30'), (8, '16:40-17:25'), (9, '18:30-19:15'), (10, '19:25-20:10'), (11, '20:20-21:05'), (12, '21:15-22:00')]),
        ),
    ]
