# Generated by Django 4.1.5 on 2023-04-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userinfo_classes_userinfo_college_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
